name: Build application
on:
  push:
    branches:
      - main
jobs:
  build-functions:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
      - name: Build
        run: |
          pnpm install
          pnpm build
     ## We then can add upload step to storage like S3 or GCS. But for now we will just attach it to GH action run
      - name: Save Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist
